# Basic
title: JL's Blog
author: JL
description: 记录下

url: "https://msgcode.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 9
paginate_path: "pages/:num/"

# Social
social:
    weibo: http://weibo.com/liubbb
    github: msgcode
    mail: 41369927@qq.com
