# Basic
title: JL's Blog
author: JL
description: 记录下

url: "https://wnglmng.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 9
paginate_path: "pages/:num/"

# Social
social:
    weibo: sunmoon1993
    github: wnglmng
    gplus: 112547382138552250597
    mail: wnglmng@gmail.com
